### ISSUE TITLE
Fix warning

### ISSUE THREAD

**Issue by akshay23** [CorlaOnline/SwiftyJSONRealmObject#4]
Please make a the quick fix for the following warning:

SwiftyJSONRealmObject.swift:24:35: 'where' clause next to generic parameters is deprecated and will be removed in the future version of Swift

**Comment by yuvarajagna** [comment]
open class func createList< T where T: SwiftyJSONRealmObject >(ofType type: T.Type, fromJson json: JSON) -> List<T> {
        let list = List<T>()
        for (_, singleJson):(String, JSON) in json {
            list.append(T(json: singleJson))
        }
        return list
    }

Getting error : Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
